PACKAGE_NAME="sysspectogram_wd"
PACKAGE_VERSION="0.9.0"
BUILT_MODULE_NAME[0]="sysspectogram_wd"
DEST_MODULE_LOCATION[0]="/kernel/extra"
AUTOINSTALL="yes"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
